### ISSUE TITLE
Cli crashes when no name is provided

### ISSUE THREAD

**Issue by JoseKilo** [BoboTiG/py-candlestick-chart#9]
HI, nice tool ! Thanks for sharing it.

I've noticed a small bug while using the cli:
If I don't provide a chart name, it crashes without providing much info:

```bash
> candlestick-chart -m json-file -f candles.json 
Traceback (most recent call last):
  File "/home/jose/charts/.venv/bin/candlestick-chart", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/jose/charts/.venv/lib/python3.11/site-packages/candlestick_chart/__main__.py", line 59, in main
    chart.draw()
  File "/home/jose/charts/.venv/lib/python3.11/site-packages/candlestick_chart/chart.py", line 57, in draw
    print(self._render())
          ^^^^^^^^^^^^^^
  File "/home/jose/charts/.venv/lib/python3.11/site-packages/candlestick_chart/chart.py", line 53, in _render
    return self.renderer.render(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jose/charts/.venv/lib/python3.11/site-packages/candlestick_chart/chart_renderer.py", line 104, in render
    output.append(chart.info_bar.render(chart_data.main_candle_set, chart_data.width))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jose/charts/.venv/lib/python3.11/site-packages/candlestick_chart/info_bar.py", line 60, in render
    " | ".join(
TypeError: object of type 'NoneType' has no len()
>
```

It works if a name is provided:

```bash
> candlestick-chart -m json-file -f candles.json --chart-name __NAME__
```

and even with an empty name:

```bash
> candlestick-chart -m json-file -f candles.json --chart-name ''
```

It looks like the default value for the argument should be a string, changing this line seems to fix it

https://github.com/BoboTiG/py-candlestick-chart/blob/e6a2a0bb8709830ae35f66675fbd2312cf8cc07a/src/candlestick_chart/__main__.py#L33

```python
    parser.add_argument("--chart-name", help="Sets the chart name.", default="")
```

I'm using the latest version from PyPI:
```bash
> candlestick-chart --version
candlestick-chart 2.6.0
```

**Comment by BoboTiG** [comment]
Thanks for the report @JoseKilo :)

Would you like to open a PR?

**Comment by BoboTiG** [comment]
I've some free time, I will work on it, and add tests at the same time.

**Comment by BoboTiG** [comment]
[v2.7.0](https://github.com/BoboTiG/py-candlestick-chart/releases/tag/v2.7.0) released with the fix 🎉

**Comment by JoseKilo** [comment]
Amazing ! Thanks a lot !!
